### ISSUE TITLE
12月1日授業内容

### ISSUE THREAD

**Issue by misatomori1217** [furuhashilab/mapping#6]
# wikidata ID紐付け作業
## 全体的な取り組み
a班、b班、c班に分かれて地名の英語表記を調べる。
a班は東京、b班は京都、c班は大阪。
## 個人的な取り組み
私はb班なので、京都の地名を担当した。
具体的にはMEMORVA(メモルヴァ)というサイトの「47都道府県 - 郵便番号一覧・地名・住所の読み方」を利用して、英語表記を調べた。

- 取り組んだ範囲
招提中町一丁目から星丘四丁目まで。

- MEMORVAの利用例
http://memorva.jp/zipcode/map.php?pref=%E5%A4%A7%E9%98%AA%E5%BA%9C&city=%E6%9E%9A%E6%96%B9%E5%B8%82&area=%E6%98%9F%E4%B8%98&zipcode=5730013

## 残りの作業

- 春日元町一丁目から東船橋二丁目

- 氷室台一丁目から藤阪西町

- 長尾台一丁目から黄金野二丁目

**Comment by mapconcierge** [comment]
こっちに集約するので閉じます。
https://github.com/furuhashilab/mapping/issues/5
