### ISSUE TITLE
12月1日　Wikidata紐付け作業

### ISSUE THREAD

**Issue by jasminever** [furuhashilab/mapping#7]
# 内容　
ABCの各班ごとに、東京、京都、大阪の地名を英語表記に書き換えるという作業。

# A班の進歩状況
個別にそれぞれが様々な場所から始めたため空欄はまばら。　
160,165,167-169,212-214,218-222,224-226,233-251,253-258,261,263,273,286,287,289-318,320-329,331-335
主に日本郵便の公式サイトを参照した。

**Comment by mapconcierge** [comment]
こっちの Issue にまとめるので閉じます。
https://github.com/furuhashilab/mapping/issues/5
